StartupEvents.registry("block", (event) => {
    event.create("diatomite")
    .displayName("Diatomite")
    .hardness(0.6)
    .resistance(0.6)
    .stoneSoundType()
    .requiresTool(false)
    .tagBlock("mineable/pickaxe")
    .texture('up', 'kubejs:block/diatomite_top')
    .texture('down', 'kubejs:block/diatomite_top')
    .texture('east', 'kubejs:block/diatomite_side')
    .texture('west', 'kubejs:block/diatomite_side')
    .texture('north', 'kubejs:block/diatomite_side')
    .texture('south', 'kubejs:block/diatomite_side')
})