StartupEvents.registry("block", (event) => {
    event.create("andesite_gravel")
    .displayName("Andesite Gravel")
    .hardness(0.6)
    .resistance(0.6)
    .gravelSoundType()
    .requiresTool(false)
    .tagBlock("mineable/shovel")
    .textureAll('kubejs:block/andesite_gravel')
})