StartupEvents.registry("block", (event) => {
    event.create("diorite_gravel")
    .displayName("Diorite Gravel")
    .hardness(0.6)
    .resistance(0.6)
    .gravelSoundType()
    .requiresTool(false)
    .tagBlock("mineable/shovel")
    .textureAll('kubejs:block/diorite_gravel')
})