StartupEvents.registry("block", (event) => {
    event.create("end_stone_gravel")
    .displayName("End Stone Gravel")
    .hardness(0.6)
    .resistance(0.6)
    .mapColor(2)
    .gravelSoundType()
    .requiresTool(false)
    .tagBlock("mineable/shovel")
    .textureAll('kubejs:block/end_stone_gravel')
})