StartupEvents.registry("block", (event) => {
    event.create("limestone_gravel")
    .displayName("Limestone Gravel")
    .hardness(0.6)
    .resistance(0.6)
    .gravelSoundType()
    .requiresTool(false)
    .tagBlock("mineable/shovel")
    .textureAll('kubejs:block/limestone_gravel')
})