StartupEvents.registry("block", (event) => {
    event.create("netherrack_gravel")
    .displayName("Netherrack Gravel")
    .hardness(0.6)
    .resistance(0.6)
    .gravelSoundType()
    .requiresTool(false)
    .tagBlock("mineable/shovel")
    .textureAll('kubejs:block/netherrack_gravel')
})